eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST}:8761/eureka/
# spring:
#   datasource:
#     initialization-mode: never
#     continue-on-error: true
  # jpa:
  #   hibernate:
  #     ddl-auto: validate
