logging:
  level:
    root: INFO
    com.poc.microservices: DEBUG
    org.springframework.web: WARN

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30  # Ensures regular heartbeat updates
    leaseExpirationDurationInSeconds: 90  # Prevents premature instance removal
