logging:
  level:
    root: INFO
    com.poc.microservices: DEBUG
    org.springframework.web: WARN

eureka:
  client:
    fetchRegistry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30  # Ensures regular heartbeat updates
    leaseExpirationDurationInSeconds: 90  # Prevents premature instance removal

logger:
  org.apache.kafka.common.config.AbstractConfig: ERROR
  org.apache.kafka.clients.admin.AdminClientConfig: ERROR
