spring:
  # jpa:
  #   open-in-view: false
  #   properties:
  #     hibernate:
  #       format_sql: true
  #       use_sql_comments: true
  #       show_sql: true        # Makes logs verbose and traceable
  #       connection.autocommit: true
  #       flushMode: AUTO
  #       connection:
  #         handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
  datasource:
    hikari:
      # auto-commit: true
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000 # 30s
      max-lifetime: 180000 # 3 mins
      connection-timeout: 10000 # 10s
    # url: jdbc:mysql://mysql-community-db.cn48a44e27uj.eu-north-1.rds.amazonaws.com:3306/employee_db
    username: admin
    # password: as ENV var

eem:
  scheduler:
    cron: "0 */2 * * * *"
    enabled: true

em:
  grpc:
    tlsEnabled: false
    hostname: poc-alb-1312740255.eu-north-1.elb.amazonaws.com
    # hostname: ${EIP}
    port: 9093

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cloud.context.scope.refresh: DEBUG

kafka:
    enabled: false
    hostname: ${HOST}

server:
  address: 0.0.0.0

jks:
  client:
    filePath: client-uat.jks
    truststore: client-truststore-uat.jks
