spring:
  datasource:
    url: jdbc:mysql://localhost:3307/employee_db
    username: root
    password: Sky_Dev#*75
    driver-class-name: com.mysql.cj.jdbc.Driver

eem:
  scheduler:
    cron: "0 */1 * * * *"
   enabled: false

logging:
  level:
    org.springframework.cloud.context.scope.refresh: DEBUG
