grpc:
  server:
    port: 9094
server:
  port: 8094
management:
  tracing:
    propagation:
      consume: [ b3, w3c ]
      produce: [ b3 ]
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: refresh, health, info, monitor
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    generate-ddl: true
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    servlet:
      path: /eem  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping

logging:
  level:
    org.springframework.cloud.context.scope.refresh: DEBUG
