management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: refresh, health, info, monitor

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/employee_db
    username: root
    password: as_ENV_var

eem:
  scheduler:
    cron: "0 */2 * * * *"
    enabled: true

logging:
  level:
    org.springframework.cloud.context.scope.refresh: DEBUG
