management:
  # zipkin:
  #   tracing:
  #     endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: refresh, health, info, monitor

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/employee_db
    username: root
    # password: as ENV var

eem:
  scheduler:
    cron: "0 */1 * * * *"
    enabled: true
em:
  grpc:
    tlsEnabled: true
    hostname: localhost
    port: 9093

logging:
  level:
    org.springframework.cloud.context.scope.refresh: DEBUG

kafka:
  enabled: true
  hostname: 127.0.0.1

jks:
  client:
    filePath: client.jks
    truststore: client-truststore.jks
