spring:
  datasource:
    url: jdbc:mysql://${HOST}:3307/employee_db
    username: root
    # password: as ENV var

eem:
  scheduler:
    cron: "0 */1 * * * *"
    enabled: false

em:
  grpc:
    tlsEnabled: true
    hostname: ${HOST}
    port: 9093

logging:
  level:
    org.springframework.cloud.context.scope.refresh: DEBUG

kafka:
  enabled: false
  hostname: ${HOST}
  port: 9092

jks:
  client:
    filePath: client.jks
    truststore: client-truststore.jks
