spring:
  application:
    name: em-service
  mvc:
    servlet:
      path: /em  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping
  datasource:
    password: Sky_Dev#*75
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
