spring:
  datasource:
    url: jdbc:mysql://localhost:3307/employer_db
    username: root
    password: Sky_Dev#*75

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
