grpc:
  server:
    port: 9093
server:
  port: 8093
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  mvc:
    servlet:
      path: /em  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping
  datasource:
    generate-ddl: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j:
  circuitbreaker:
    instances:
      eemCircuitBreaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 3
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5

eem:
  fallback:
    cache-enabled: true
    cache-path: ${java.io.tmpdir}/eem/working-hours.csv

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, monitor
  tracing:
    propagation:
      consume: [ b3, w3c ]
      produce: [ b3 ]
    sampling:
      probability: 1.0
