spring:
  jpa:
    properties:
      hibernate:
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
  datasource:
    hikari:
      maximum-pool-size: 10
    # url: jdbc:mysql://mysql-community-db.cn48a44e27uj.eu-north-1.rds.amazonaws.com:3306/employer_db
    username: admin
    # password: as ENV var

server:
  address: 0.0.0.0
