spring:
  datasource:
    url: jdbc:mysql://${HOST}:3307/employer_db
    username: root
    # password: as ENV var

jks:
  server:
    filePath: server.jks
    truststore: server-truststore.jks

grpc:  
  tls-enabled: true
