em:
  graphql:
    url: http://${HOST}/em/graphql
    service: http://api-gateway/em-service/em/graphql

kafka:
  hostname: 13.61.132.105
  port: 9092
  enabled: true

server:
  address: 0.0.0.0

jks:
  client:
    filePath: client-uat.jks
    truststore: client-truststore-uat.jks

spring:
  kafka:
    security:
      protocol: "SSL"
    ssl:
      trust-store-location: classpath:/client-truststore-uat.jks
      trust-store-password: ${JKS_KEY}
      key-store-location:  classpath:/client-uat.jks
      key-store-password: ${JKS_KEY}
