em:
  graphql:
    url: http://${HOST}/em/graphql
    service: http://api-gateway/em-service/em/graphql

kafka:
    enabled: true
    # hostname: localhost
    # port: 9092

spring:
  kafka:
    bootstrap-servers: localhost:9092
