server:
  port: 8091
spring:
  config:
    import: optional:configserver:configserver
  cloud:
    openfeign:
      okhttp:
        enabled: true
  application:
    name: mas-service
  mvc:
    servlet:
      path: /mas  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping

security:
  excludedEndpoints: "/mas/mas-users/login,/mas/mas-users/register"
