server:
  port: 8092
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: uam-service
  mvc:
    servlet:
      path: /uam  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping
  datasource:
    url: jdbc:mysql://localhost:3307/user_auth_db
    username: root
#    password: Sky_Dev#*75

logging:
  level:
    root: INFO
    com.poc.microservices: DEBUG
    org.springframework.web: WARN

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

jwt:
#  secretKey: ENV var SECRET_KEY
  expirationMinutes: 60
