spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000 # 30s
      max-lifetime: 180000 # 3 mins
      connection-timeout: 10000 # 10s
    # url: jdbc:mysql://mysql-community-db.cn48a44e27uj.eu-north-1.rds.amazonaws.com:3306/user_auth_db
    username: admin
    # password: as ENV var
server:
  address: 0.0.0.0
