server:
  port: 8092
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  mvc:
    servlet:
      path: /uam  # This sets the global prefix for all controllers
    pathmatch:
      matching-strategy: ant_path_matcher  # Ensures correct path mapping

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

jwt:
#  secretKey: ENV var SECRET_KEY
  expirationMinutes: 60
